version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
   
    commands:
        # install npm
        - npm install --force
       
  build:
    commands:
        # run build script
        - npm run build

     
artifacts:
  files: '**/*'
  discard-paths: yes